name: Bug Report
description: 버그를 보고하고 수정하기 위한 정식 양식입니다.
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        정확한 버그 수정을 위해 아래 정보를 상세히 작성해 주세요.
  - type: textarea
    id: bug-description
    attributes:
      label: 버그 상황 설명
      description: 어떤 버그가 발생했는지 명확하게 설명해 주세요.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 재현 방법
      description: 버그를 재현하기 위한 단계를 순서대로 적어주세요.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: 환경 정보
      placeholder: "예: Ubuntu 24.04, MacOS, Chrome 120"
  - type: textarea
    id: screenshots
    attributes:
      label: 스크린샷 및 로그 (선택)
      description: 이미지나 에러 로그를 이곳에 첨부해 주세요.
